alias: Mülltonne Benachrichtigung
description: Benachrichtigt vor der Müllabholung mit dauerhafter Benachrichtigung
trigger:
  - platform: time
    at: "{{ trigger_time }}"
    id: Uhrzeit
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: RAUSGESTELLT
    id: Rausgestellt
condition:
  - condition: template
    value_template: "{{ states('sensor.1').split(' in ')[1].split(' ')[0] | int == 1 }}"
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Uhrzeit
            enabled: false
        sequence:
          - action: notify.mobile_app_tillis_handy
            data:
              message: >
                {% set muellart = states('sensor.1').split(' in ')[0] %} 
                {% if muellart == 'Gelbe Säcke' %}
                  Morgen werden die Gelben Säcke abgeholt!
                {% elif muellart == 'Restmülltonne' %}
                  Morgen wird die Restmülltonne abgeholt!
                {% elif muellart == 'Papiertonne' %}
                  Morgen wird die Papiertonne abgeholt!
                {% else %}
                  Morgen wird {{ muellart }} abgeholt!
                {% endif %}
              title: Müllabholung morgen
              data:
                persistent: true
                sticky: true
                channel: muell_erinnerung
                importance: high
                ttl: 0
                priority: high
                tag: muell_erinnerung
                actions:
                  - action: RAUSGESTELLT
                    title: Rausgestellt
          - wait_for_trigger:
              - platform: event
                event_type: mobile_app_notification_action
                event_data:
                  action: RAUSGESTELLT
          - action: notify.mobile_app_tillis_handy
            data:
              message: "Danke für die Bestätigung :) "
              title: "{{ states('sensor.1').split(' in ')[0] }} wurden rausgestellt!"
              data:
                tag: muell_erinnerung
                channel: muell_erinnerung
                importance: high
                priority: high
          - delay:
              seconds: 5
          - action: notify.mobile_app_tillis_handy
            data:
              message: clear_notification
              data:
                tag: muell_erinnerung
                channel: muell_erinnerung
mode: single
